### ISSUE TITLE
Build Norwegian dictionaries from upstream

### ISSUE THREAD

**Issue by jhanschoo** [LibreOffice/dictionaries#12]
The last release in 2016 can be obtained from https://alioth-archive.debian.org/releases/spell-norwegian/spell-norwegian/2.2/ .

The upstream source repository Alioth has been deprecated this month in favor of the GitLab-based Salsa. Debian packaging seems to be maintained at https://salsa.debian.org/tfheen/norwegian .

**Comment by jhanschoo** [comment]
I just realized from another issue that LibreOffice does not maintain bug reports here, but accept patches elsewhere. Closing the issue.

**Comment by fitojb** [comment]
This is now solved with commit 5b81821a17bf104942b364ad7e13ab4cd8f5ec50.

For bug reports and update requests, please use our bug tracker at [bugs.documentfoundation.org](https://bugs.documentfoundation.org).
