### ISSUE TITLE
Bug: etc is marked as a spelling mistake in british english

### ISSUE THREAD

**Issue by sbrl** [LibreOffice/dictionaries#18]
As per pbek/QOwnNotes#1399, if I type `etc.` in QOwnNotes I find that `etc.` is marked as a spelling mistake - even though it's in the British dictionary as `etc.` - so it corrects it to `etc.` - which results in `etc..` - and the cycle continues.

QOwnNotes isn't the only program I see this bug in.

**Comment by pbek** [comment]
As far as I can see all dictionaries with abbreviations ending with a `.` are afflicted, like https://github.com/LibreOffice/dictionaries/blob/master/de/de_AT_frami.dic or https://github.com/LibreOffice/dictionaries/blob/master/de/de_DE_frami.dic.

https://github.com/LibreOffice/dictionaries/blob/41c5fc0693d6ca4a0934d859ebb39659339e968d/en/en_US.dic#L22138 doesn't have a training `.`, so it works fine.

https://github.com/LibreOffice/dictionaries/blob/41c5fc0693d6ca4a0934d859ebb39659339e968d/en/en_GB.dic#L26812 has a trailing `.`, so it doesn't work.

Maybe removing all trailing `.` from the dictionaries is the solution.

**Comment by sbrl** [comment]
I see, @repo-lockdown. It would have been very helpful if you had told me that a year ago when I opened the issue......

That bug reporting process seems so convoluted and complex I'm not sure I can be bothered to report this, given I only use LibreOffice at all on average once or twice a year (I generally use a simple text editor most of the time).

**Comment by marcoagpinto** [comment]
The solution is to improve the Hunspell engine.

"etc." has a period in British, so it has a period in the .dic .

If I remove the period, LibreOffice won't suggest for it to be added, which is incorrect behaviour.

**Comment by sbrl** [comment]
In that case @marcoagpinto, I guess we should report this as an issue in hunspell, not Libreoffice.
