### ISSUE TITLE
Adding Persian/Farsi

### ISSUE THREAD

**Issue by reza1615** [LibreOffice/dictionaries#22]
There is Persian/Farsi dictionary in [Lilak](https://github.com/b00f/lilak) project. Based on [here](https://github.com/b00f/lilak#using-lilak) some famous project used their data. [Final release](https://github.com/b00f/lilak/releases/)
Please add it to the language dictionary.

**Comment by hoomanist** [comment]
i agree

**Comment by vbeh** [comment]
that would be great!
[fa-IR.zip](https://github.com/LibreOffice/dictionaries/files/4812671/fa-IR.zip)

**Comment by ilmari-lauhakangas** [comment]
This repo is read-only, please submit through Gerrit: https://wiki.documentfoundation.org/Development/Dictionaries#Adding.2FUpdating_bundled_Dictionaries
