### ISSUE TITLE
Persian  dictionary

### ISSUE THREAD

**Issue by vbeh** [LibreOffice/dictionaries#31]
hello everybody 
there is a Persian/Farsi dictionary designed for Hunspell and all the files are available here: 
[https://github.com/b00f/lilak](url)
latest vesion: [https://github.com/b00f/lilak/releases/](url)
it's a good project with native Persian speakers constantly updating it. 
we opened a ticket here but for some reason after almost one year it is not added to LibreOffice (or i can't see it). 
this is the first ticket: 
[https://github.com/LibreOffice/dictionaries/issues/22](url)
thank you all for the hard work.

**Comment by ilmari-lauhakangas** [comment]
This repo is read-only, please submit through Gerrit: https://wiki.documentfoundation.org/Development/Dictionaries#Adding.2FUpdating_bundled_Dictionaries
