### ISSUE TITLE
en_GB: "notarisation" word is missing?

### ISSUE THREAD

**Issue by adamshakhabov** [LibreOffice/dictionaries#36]
I connected [en_GB.dic](https://github.com/LibreOffice/dictionaries/blob/master/en/en_GB.dic) and [en_GB.aff](https://github.com/LibreOffice/dictionaries/blob/master/en/en_GB.aff) to one of [Hunspell port](https://www.nuget.org/packages/WeCantSpell.Hunspell/) for my programming language. It says "**notarisation**" is misspelled. MS Word says not.

That word has a different form for US (notari**Z**ation) and UK (notari**S**ation).

Is there is some issue with I use Hunspell port (for example, it does not correctly use rules from .aff) or the above dictionary problem?

**Comment by marcoagpinto** [comment]
https://www.lexico.com/en/definition/notarization

Oxford says that both words are chiefly US.

I checked in this public site of Oxford and on its other using my Premium account.

I will ask an expert soon to be 100% sure.

**Comment by marcoagpinto** [comment]
@adamshakhabov 

Confirmed!

I will add both in the next release (1-JAN-2022).

Thanks!

**Comment by adamshakhabov** [comment]
@marcoagpinto, many thanks for the quick reply!

They confirmed that both forms are US word?

**Comment by marcoagpinto** [comment]
@adamshakhabov 

They confirmed that the words appear in a few dictionaries not mentioning it is US, so it can be added.

I will add it on Monday, and it will come in the next .oxt for LibreOffice and OpenOffice (1-JAN-2022).

**Comment by marcoagpinto** [comment]
Done!

79788) notarisation
79789) notarisation's
79790) notarisations
79791) notarization
79792) notarization's
79793) notarizations
