### ISSUE TITLE
Upgrade polish

### ISSUE THREAD

**Issue by EvanCarroll** [LibreOffice/dictionaries#5]
https://github.com/lemonskyjwt/plpstgrssearch/pull/2

The polish dict is version at 2017-05-14. The newest version 2017-11-10. I will look at fixing this. Not sure what it takes to generate with new versions, or if it is a part of the build system. Will investigate 2017-11-13.

**Comment by fitojb** [comment]
Hi,

We’ll gladly accept a patch at gerrit.libreoffice.org; we don’t use GitHub PRs. For instructions on how to submit a patch to us, check out [this wiki page](https://wiki.documentfoundation.org/Gerrit). Let me know if you have any questions!
