### ISSUE TITLE
Whare are the LO Dictionaries?

### ISSUE THREAD

**Issue by TopView** [LibreOffice/dictionaries#8]
The README file only says, "Contains dictionaries related code and data".

Please add a description to either the Git Wiki or the README saying what the LO dictionaries are, what they're used for and who needs to be installing them.  

Also how are these related to the translations?

Thanks.

ref:  https://www.libreoffice.org/download/download/?type=deb-x86_64&version=6.0.0&lang=en-US

**Comment by fitojb** [comment]
I’ve now added a link in commit d8d2411.
